---

  - name: add group dba
    group: name=dba system=yes state=present

  - file: path=/u01/app state=directory

  - name: add user oracle
    user: name=oracle system=yes group=dba home=/u01/app/oracle shell=/bin/bash state=present

  - file: path=/u01/app/oracle owner=oracle group=dba recurse=yes state=directory

  - apt: name=python-boto state=latest update_cache=yes cache_valid_time=3600

  - s3: bucket=bsg-binaries object=oracle-xe_11.2.0-2_amd64.deb dest=/tmp/oracle-xe_11.2.0-2_amd64.deb mode=get aws_access_key={{aws_key}} aws_secret_key={{aws_seckey}}

  - file: path=/tmp/oracle-xe_11.2.0-2_amd64.deb owner=root group=root mode=0755 state=file

#  - copy: src={{item}} dest=/tmp/ owner=root group=root mode=0755
#    with_fileglob:
#      - oracle-xe*.deb

  - include: oracle-xe-install-debian.yml
    when: ansible_os_family == "Debian"

  - include: oracle-xe-install-redhat.yml
    when: ansible_os_family == "RedHat"

#  - include: oracle-xe-install-suse.yml
#    when: ansible_os_family == "Suse"
